baseURL = 'https://stringcase.org/'
languageCode = 'en-us'
title = 'stringcase.org'
theme = 'hextra'
# https://imfing.github.io/hextra/docs/

[markup.highlight]
style = "catppuccin-mocha"

[params.theme]
default = "light"
displayToggle = true

[[menu.main]]
name = "Definition"
pageRef = "/definition"
weight = 1

[[menu.main]]
name = "Cases"
pageRef = "/cases"
weight = 2

[[menu.main]]
name = "About"
pageRef = "/about"
weight = 3